// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2-devel
// 	protoc        v4.25.1
// source: audio.proto

package audio

import (
	track "github.com/openimsdk/openim-rtc/proto/go/track"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AudioStreamType int32

const (
	AudioStreamType_AUDIO_STREAM_NATIVE AudioStreamType = 0
	AudioStreamType_AUDIO_STREAM_HTML   AudioStreamType = 1
)

// Enum value maps for AudioStreamType.
var (
	AudioStreamType_name = map[int32]string{
		0: "AUDIO_STREAM_NATIVE",
		1: "AUDIO_STREAM_HTML",
	}
	AudioStreamType_value = map[string]int32{
		"AUDIO_STREAM_NATIVE": 0,
		"AUDIO_STREAM_HTML":   1,
	}
)

func (x AudioStreamType) Enum() *AudioStreamType {
	p := new(AudioStreamType)
	*p = x
	return p
}

func (x AudioStreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioStreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_audio_proto_enumTypes[0].Descriptor()
}

func (AudioStreamType) Type() protoreflect.EnumType {
	return &file_audio_proto_enumTypes[0]
}

func (x AudioStreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioStreamType.Descriptor instead.
func (AudioStreamType) EnumDescriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{0}
}

type AudioSourceType int32

const (
	AudioSourceType_AUDIO_SOURCE_NATIVE AudioSourceType = 0
)

// Enum value maps for AudioSourceType.
var (
	AudioSourceType_name = map[int32]string{
		0: "AUDIO_SOURCE_NATIVE",
	}
	AudioSourceType_value = map[string]int32{
		"AUDIO_SOURCE_NATIVE": 0,
	}
)

func (x AudioSourceType) Enum() *AudioSourceType {
	p := new(AudioSourceType)
	*p = x
	return p
}

func (x AudioSourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioSourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_audio_proto_enumTypes[1].Descriptor()
}

func (AudioSourceType) Type() protoreflect.EnumType {
	return &file_audio_proto_enumTypes[1]
}

func (x AudioSourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioSourceType.Descriptor instead.
func (AudioSourceType) EnumDescriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{1}
}

type AudioStreamInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type AudioStreamType `protobuf:"varint,1,opt,name=type,proto3,enum=openim.rtc.audio.AudioStreamType" json:"type"`
}

func (x *AudioStreamInfo) Reset() {
	*x = AudioStreamInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioStreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStreamInfo) ProtoMessage() {}

func (x *AudioStreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStreamInfo.ProtoReflect.Descriptor instead.
func (*AudioStreamInfo) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{0}
}

func (x *AudioStreamInfo) GetType() AudioStreamType {
	if x != nil {
		return x.Type
	}
	return AudioStreamType_AUDIO_STREAM_NATIVE
}

type OwnedAudioStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Handle uint64           `protobuf:"varint,1,opt,name=handle,proto3" json:"handle"`
	Info   *AudioStreamInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info"`
}

func (x *OwnedAudioStream) Reset() {
	*x = OwnedAudioStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnedAudioStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedAudioStream) ProtoMessage() {}

func (x *OwnedAudioStream) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedAudioStream.ProtoReflect.Descriptor instead.
func (*OwnedAudioStream) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{1}
}

func (x *OwnedAudioStream) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *OwnedAudioStream) GetInfo() *AudioStreamInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type AudioSourceOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EchoCancellation bool `protobuf:"varint,1,opt,name=echo_cancellation,json=echoCancellation,proto3" json:"echo_cancellation"`
	NoiseSuppression bool `protobuf:"varint,2,opt,name=noise_suppression,json=noiseSuppression,proto3" json:"noise_suppression"`
	AutoGainControl  bool `protobuf:"varint,3,opt,name=auto_gain_control,json=autoGainControl,proto3" json:"auto_gain_control"`
}

func (x *AudioSourceOptions) Reset() {
	*x = AudioSourceOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioSourceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioSourceOptions) ProtoMessage() {}

func (x *AudioSourceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioSourceOptions.ProtoReflect.Descriptor instead.
func (*AudioSourceOptions) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{2}
}

func (x *AudioSourceOptions) GetEchoCancellation() bool {
	if x != nil {
		return x.EchoCancellation
	}
	return false
}

func (x *AudioSourceOptions) GetNoiseSuppression() bool {
	if x != nil {
		return x.NoiseSuppression
	}
	return false
}

func (x *AudioSourceOptions) GetAutoGainControl() bool {
	if x != nil {
		return x.AutoGainControl
	}
	return false
}

type AudioSourceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type AudioSourceType `protobuf:"varint,1,opt,name=type,proto3,enum=openim.rtc.audio.AudioSourceType" json:"type"`
}

func (x *AudioSourceInfo) Reset() {
	*x = AudioSourceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioSourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioSourceInfo) ProtoMessage() {}

func (x *AudioSourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioSourceInfo.ProtoReflect.Descriptor instead.
func (*AudioSourceInfo) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{3}
}

func (x *AudioSourceInfo) GetType() AudioSourceType {
	if x != nil {
		return x.Type
	}
	return AudioSourceType_AUDIO_SOURCE_NATIVE
}

type OwnedAudioSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Handle uint64           `protobuf:"varint,1,opt,name=handle,proto3" json:"handle"`
	Info   *AudioSourceInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info"`
}

func (x *OwnedAudioSource) Reset() {
	*x = OwnedAudioSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnedAudioSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedAudioSource) ProtoMessage() {}

func (x *OwnedAudioSource) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedAudioSource.ProtoReflect.Descriptor instead.
func (*OwnedAudioSource) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{4}
}

func (x *OwnedAudioSource) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *OwnedAudioSource) GetInfo() *AudioSourceInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type AudioFrameBufferInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataPtr           uint64 `protobuf:"varint,1,opt,name=data_ptr,json=dataPtr,proto3" json:"data_ptr"` // *const i16
	NumChannels       uint32 `protobuf:"varint,2,opt,name=num_channels,json=numChannels,proto3" json:"num_channels"`
	SampleRate        uint32 `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate"`
	SamplesPerChannel uint32 `protobuf:"varint,4,opt,name=samples_per_channel,json=samplesPerChannel,proto3" json:"samples_per_channel"`
}

func (x *AudioFrameBufferInfo) Reset() {
	*x = AudioFrameBufferInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioFrameBufferInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFrameBufferInfo) ProtoMessage() {}

func (x *AudioFrameBufferInfo) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFrameBufferInfo.ProtoReflect.Descriptor instead.
func (*AudioFrameBufferInfo) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{5}
}

func (x *AudioFrameBufferInfo) GetDataPtr() uint64 {
	if x != nil {
		return x.DataPtr
	}
	return 0
}

func (x *AudioFrameBufferInfo) GetNumChannels() uint32 {
	if x != nil {
		return x.NumChannels
	}
	return 0
}

func (x *AudioFrameBufferInfo) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioFrameBufferInfo) GetSamplesPerChannel() uint32 {
	if x != nil {
		return x.SamplesPerChannel
	}
	return 0
}

type OwnedAudioFrameBuffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Handle uint64                `protobuf:"varint,1,opt,name=handle,proto3" json:"handle"`
	Info   *AudioFrameBufferInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info"`
}

func (x *OwnedAudioFrameBuffer) Reset() {
	*x = OwnedAudioFrameBuffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnedAudioFrameBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedAudioFrameBuffer) ProtoMessage() {}

func (x *OwnedAudioFrameBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedAudioFrameBuffer.ProtoReflect.Descriptor instead.
func (*OwnedAudioFrameBuffer) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{6}
}

func (x *OwnedAudioFrameBuffer) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *OwnedAudioFrameBuffer) GetInfo() *AudioFrameBufferInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type AudioResamplerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AudioResamplerInfo) Reset() {
	*x = AudioResamplerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioResamplerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioResamplerInfo) ProtoMessage() {}

func (x *AudioResamplerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioResamplerInfo.ProtoReflect.Descriptor instead.
func (*AudioResamplerInfo) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{7}
}

type OwnedAudioResampler struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Handle uint64              `protobuf:"varint,1,opt,name=handle,proto3" json:"handle"`
	Info   *AudioResamplerInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info"`
}

func (x *OwnedAudioResampler) Reset() {
	*x = OwnedAudioResampler{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnedAudioResampler) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedAudioResampler) ProtoMessage() {}

func (x *OwnedAudioResampler) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedAudioResampler.ProtoReflect.Descriptor instead.
func (*OwnedAudioResampler) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{8}
}

func (x *OwnedAudioResampler) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *OwnedAudioResampler) GetInfo() *AudioResamplerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type NewAudioStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackHandle uint64          `protobuf:"varint,1,opt,name=track_handle,json=trackHandle,proto3" json:"track_handle"`
	Type        AudioStreamType `protobuf:"varint,2,opt,name=type,proto3,enum=openim.rtc.audio.AudioStreamType" json:"type"`
	SampleRate  uint32          `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate"`
	NumChannels uint32          `protobuf:"varint,4,opt,name=num_channels,json=numChannels,proto3" json:"num_channels"`
}

func (x *NewAudioStreamReq) Reset() {
	*x = NewAudioStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAudioStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAudioStreamReq) ProtoMessage() {}

func (x *NewAudioStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAudioStreamReq.ProtoReflect.Descriptor instead.
func (*NewAudioStreamReq) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{9}
}

func (x *NewAudioStreamReq) GetTrackHandle() uint64 {
	if x != nil {
		return x.TrackHandle
	}
	return 0
}

func (x *NewAudioStreamReq) GetType() AudioStreamType {
	if x != nil {
		return x.Type
	}
	return AudioStreamType_AUDIO_STREAM_NATIVE
}

func (x *NewAudioStreamReq) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *NewAudioStreamReq) GetNumChannels() uint32 {
	if x != nil {
		return x.NumChannels
	}
	return 0
}

type NewAudioStreamRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stream *OwnedAudioStream `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream"`
}

func (x *NewAudioStreamRes) Reset() {
	*x = NewAudioStreamRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAudioStreamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAudioStreamRes) ProtoMessage() {}

func (x *NewAudioStreamRes) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAudioStreamRes.ProtoReflect.Descriptor instead.
func (*NewAudioStreamRes) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{10}
}

func (x *NewAudioStreamRes) GetStream() *OwnedAudioStream {
	if x != nil {
		return x.Stream
	}
	return nil
}

type NewAudioSourceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        AudioSourceType     `protobuf:"varint,1,opt,name=type,proto3,enum=openim.rtc.audio.AudioSourceType" json:"type"`
	Options     *AudioSourceOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options"`
	SampleRate  uint32              `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate"`
	NumChannels uint32              `protobuf:"varint,4,opt,name=num_channels,json=numChannels,proto3" json:"num_channels"`
	QueueSizeMs uint32              `protobuf:"varint,5,opt,name=queue_size_ms,json=queueSizeMs,proto3" json:"queue_size_ms"`
}

func (x *NewAudioSourceReq) Reset() {
	*x = NewAudioSourceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAudioSourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAudioSourceReq) ProtoMessage() {}

func (x *NewAudioSourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAudioSourceReq.ProtoReflect.Descriptor instead.
func (*NewAudioSourceReq) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{11}
}

func (x *NewAudioSourceReq) GetType() AudioSourceType {
	if x != nil {
		return x.Type
	}
	return AudioSourceType_AUDIO_SOURCE_NATIVE
}

func (x *NewAudioSourceReq) GetOptions() *AudioSourceOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *NewAudioSourceReq) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *NewAudioSourceReq) GetNumChannels() uint32 {
	if x != nil {
		return x.NumChannels
	}
	return 0
}

func (x *NewAudioSourceReq) GetQueueSizeMs() uint32 {
	if x != nil {
		return x.QueueSizeMs
	}
	return 0
}

type NewAudioSourceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source *OwnedAudioSource `protobuf:"bytes,1,opt,name=source,proto3" json:"source"`
}

func (x *NewAudioSourceRes) Reset() {
	*x = NewAudioSourceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAudioSourceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAudioSourceRes) ProtoMessage() {}

func (x *NewAudioSourceRes) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAudioSourceRes.ProtoReflect.Descriptor instead.
func (*NewAudioSourceRes) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{12}
}

func (x *NewAudioSourceRes) GetSource() *OwnedAudioSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type CaptureAudioFrameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceHandle uint64                `protobuf:"varint,1,opt,name=source_handle,json=sourceHandle,proto3" json:"source_handle"`
	Buffer       *AudioFrameBufferInfo `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer"`
}

func (x *CaptureAudioFrameReq) Reset() {
	*x = CaptureAudioFrameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureAudioFrameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureAudioFrameReq) ProtoMessage() {}

func (x *CaptureAudioFrameReq) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureAudioFrameReq.ProtoReflect.Descriptor instead.
func (*CaptureAudioFrameReq) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{13}
}

func (x *CaptureAudioFrameReq) GetSourceHandle() uint64 {
	if x != nil {
		return x.SourceHandle
	}
	return 0
}

func (x *CaptureAudioFrameReq) GetBuffer() *AudioFrameBufferInfo {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type CaptureAudioFrameRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CaptureAudioFrameRes) Reset() {
	*x = CaptureAudioFrameRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureAudioFrameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureAudioFrameRes) ProtoMessage() {}

func (x *CaptureAudioFrameRes) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureAudioFrameRes.ProtoReflect.Descriptor instead.
func (*CaptureAudioFrameRes) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{14}
}

type ClearAudioBufferReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceHandle uint64 `protobuf:"varint,1,opt,name=source_handle,json=sourceHandle,proto3" json:"source_handle"`
}

func (x *ClearAudioBufferReq) Reset() {
	*x = ClearAudioBufferReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearAudioBufferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAudioBufferReq) ProtoMessage() {}

func (x *ClearAudioBufferReq) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAudioBufferReq.ProtoReflect.Descriptor instead.
func (*ClearAudioBufferReq) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{15}
}

func (x *ClearAudioBufferReq) GetSourceHandle() uint64 {
	if x != nil {
		return x.SourceHandle
	}
	return 0
}

type ClearAudioBufferRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClearAudioBufferRes) Reset() {
	*x = ClearAudioBufferRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearAudioBufferRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAudioBufferRes) ProtoMessage() {}

func (x *ClearAudioBufferRes) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAudioBufferRes.ProtoReflect.Descriptor instead.
func (*ClearAudioBufferRes) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{16}
}

type NewAudioResamplerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewAudioResamplerReq) Reset() {
	*x = NewAudioResamplerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAudioResamplerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAudioResamplerReq) ProtoMessage() {}

func (x *NewAudioResamplerReq) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAudioResamplerReq.ProtoReflect.Descriptor instead.
func (*NewAudioResamplerReq) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{17}
}

type NewAudioResamplerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resampler *OwnedAudioResampler `protobuf:"bytes,1,opt,name=resampler,proto3" json:"resampler"`
}

func (x *NewAudioResamplerRes) Reset() {
	*x = NewAudioResamplerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewAudioResamplerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAudioResamplerRes) ProtoMessage() {}

func (x *NewAudioResamplerRes) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAudioResamplerRes.ProtoReflect.Descriptor instead.
func (*NewAudioResamplerRes) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{18}
}

func (x *NewAudioResamplerRes) GetResampler() *OwnedAudioResampler {
	if x != nil {
		return x.Resampler
	}
	return nil
}

type RemixAndResampleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResamplerHandle uint64                `protobuf:"varint,1,opt,name=resampler_handle,json=resamplerHandle,proto3" json:"resampler_handle"`
	Buffer          *AudioFrameBufferInfo `protobuf:"bytes,2,opt,name=buffer,proto3" json:"buffer"`
	NumChannels     uint32                `protobuf:"varint,3,opt,name=num_channels,json=numChannels,proto3" json:"num_channels"`
	SampleRate      uint32                `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate"`
}

func (x *RemixAndResampleReq) Reset() {
	*x = RemixAndResampleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemixAndResampleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemixAndResampleReq) ProtoMessage() {}

func (x *RemixAndResampleReq) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemixAndResampleReq.ProtoReflect.Descriptor instead.
func (*RemixAndResampleReq) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{19}
}

func (x *RemixAndResampleReq) GetResamplerHandle() uint64 {
	if x != nil {
		return x.ResamplerHandle
	}
	return 0
}

func (x *RemixAndResampleReq) GetBuffer() *AudioFrameBufferInfo {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *RemixAndResampleReq) GetNumChannels() uint32 {
	if x != nil {
		return x.NumChannels
	}
	return 0
}

func (x *RemixAndResampleReq) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type RemixAndResampleRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buffer *OwnedAudioFrameBuffer `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer"`
}

func (x *RemixAndResampleRes) Reset() {
	*x = RemixAndResampleRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemixAndResampleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemixAndResampleRes) ProtoMessage() {}

func (x *RemixAndResampleRes) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemixAndResampleRes.ProtoReflect.Descriptor instead.
func (*RemixAndResampleRes) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{20}
}

func (x *RemixAndResampleRes) GetBuffer() *OwnedAudioFrameBuffer {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type AudioStreamFromParticipantReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParticipantHandle uint64            `protobuf:"varint,1,opt,name=participant_handle,json=participantHandle,proto3" json:"participant_handle"`
	Type              AudioStreamType   `protobuf:"varint,2,opt,name=type,proto3,enum=openim.rtc.audio.AudioStreamType" json:"type"`
	TrackSource       track.TrackSource `protobuf:"varint,3,opt,name=track_source,json=trackSource,proto3,enum=openim.rtc.track.TrackSource" json:"track_source"`
	SampleRate        uint32            `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate"`
	NumChannels       uint32            `protobuf:"varint,6,opt,name=num_channels,json=numChannels,proto3" json:"num_channels"`
}

func (x *AudioStreamFromParticipantReq) Reset() {
	*x = AudioStreamFromParticipantReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioStreamFromParticipantReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStreamFromParticipantReq) ProtoMessage() {}

func (x *AudioStreamFromParticipantReq) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStreamFromParticipantReq.ProtoReflect.Descriptor instead.
func (*AudioStreamFromParticipantReq) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{21}
}

func (x *AudioStreamFromParticipantReq) GetParticipantHandle() uint64 {
	if x != nil {
		return x.ParticipantHandle
	}
	return 0
}

func (x *AudioStreamFromParticipantReq) GetType() AudioStreamType {
	if x != nil {
		return x.Type
	}
	return AudioStreamType_AUDIO_STREAM_NATIVE
}

func (x *AudioStreamFromParticipantReq) GetTrackSource() track.TrackSource {
	if x != nil {
		return x.TrackSource
	}
	return track.TrackSource(0)
}

func (x *AudioStreamFromParticipantReq) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioStreamFromParticipantReq) GetNumChannels() uint32 {
	if x != nil {
		return x.NumChannels
	}
	return 0
}

type AudioStreamFromParticipantRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AudioStreamFromParticipantRes) Reset() {
	*x = AudioStreamFromParticipantRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioStreamFromParticipantRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStreamFromParticipantRes) ProtoMessage() {}

func (x *AudioStreamFromParticipantRes) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStreamFromParticipantRes.ProtoReflect.Descriptor instead.
func (*AudioStreamFromParticipantRes) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{22}
}

type AudioFrameReceived struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame *OwnedAudioFrameBuffer `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame"`
}

func (x *AudioFrameReceived) Reset() {
	*x = AudioFrameReceived{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioFrameReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFrameReceived) ProtoMessage() {}

func (x *AudioFrameReceived) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFrameReceived.ProtoReflect.Descriptor instead.
func (*AudioFrameReceived) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{23}
}

func (x *AudioFrameReceived) GetFrame() *OwnedAudioFrameBuffer {
	if x != nil {
		return x.Frame
	}
	return nil
}

type AudioStreamEOS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AudioStreamEOS) Reset() {
	*x = AudioStreamEOS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioStreamEOS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStreamEOS) ProtoMessage() {}

func (x *AudioStreamEOS) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStreamEOS.ProtoReflect.Descriptor instead.
func (*AudioStreamEOS) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{24}
}

type AudioStreamEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamHandle uint64 `protobuf:"varint,1,opt,name=stream_handle,json=streamHandle,proto3" json:"stream_handle"`
	// Types that are assignable to Message:
	//
	//	*AudioStreamEvent_FrameReceived
	//	*AudioStreamEvent_Eos
	Message isAudioStreamEvent_Message `protobuf_oneof:"message"`
}

func (x *AudioStreamEvent) Reset() {
	*x = AudioStreamEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audio_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioStreamEvent) ProtoMessage() {}

func (x *AudioStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_audio_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioStreamEvent.ProtoReflect.Descriptor instead.
func (*AudioStreamEvent) Descriptor() ([]byte, []int) {
	return file_audio_proto_rawDescGZIP(), []int{25}
}

func (x *AudioStreamEvent) GetStreamHandle() uint64 {
	if x != nil {
		return x.StreamHandle
	}
	return 0
}

func (m *AudioStreamEvent) GetMessage() isAudioStreamEvent_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *AudioStreamEvent) GetFrameReceived() *AudioFrameReceived {
	if x, ok := x.GetMessage().(*AudioStreamEvent_FrameReceived); ok {
		return x.FrameReceived
	}
	return nil
}

func (x *AudioStreamEvent) GetEos() *AudioStreamEOS {
	if x, ok := x.GetMessage().(*AudioStreamEvent_Eos); ok {
		return x.Eos
	}
	return nil
}

type isAudioStreamEvent_Message interface {
	isAudioStreamEvent_Message()
}

type AudioStreamEvent_FrameReceived struct {
	FrameReceived *AudioFrameReceived `protobuf:"bytes,2,opt,name=frame_received,json=frameReceived,proto3,oneof"`
}

type AudioStreamEvent_Eos struct {
	Eos *AudioStreamEOS `protobuf:"bytes,3,opt,name=eos,proto3,oneof"`
}

func (*AudioStreamEvent_FrameReceived) isAudioStreamEvent_Message() {}

func (*AudioStreamEvent_Eos) isAudioStreamEvent_Message() {}

var File_audio_proto protoreflect.FileDescriptor

var file_audio_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x1a,
	0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0f,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x61, 0x0a, 0x10, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75,
	0x64, 0x69, 0x6f, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x9a, 0x01, 0x0a, 0x12, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x2b, 0x0a, 0x11, 0x65, 0x63, 0x68, 0x6f, 0x5f, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x65, 0x63, 0x68,
	0x6f, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a,
	0x11, 0x6e, 0x6f, 0x69, 0x73, 0x65, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x6e, 0x6f, 0x69, 0x73, 0x65, 0x53,
	0x75, 0x70, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x11, 0x61, 0x75,
	0x74, 0x6f, 0x5f, 0x67, 0x61, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x61, 0x75, 0x74, 0x6f, 0x47, 0x61, 0x69, 0x6e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x22, 0x48, 0x0a, 0x0f, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d,
	0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x61, 0x0a, 0x10, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x35, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0xa5, 0x01, 0x0a, 0x14, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x64, 0x61, 0x74, 0x61, 0x50, 0x74, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x5f, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6e,
	0x75, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x73,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x50, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x6b, 0x0a, 0x15, 0x4f,
	0x77, 0x6e, 0x65, 0x64, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x42, 0x75,
	0x66, 0x66, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x3a, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x52, 0x65, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x67,
	0x0a, 0x13, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x38, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a,
	0x0c, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21,
	0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69,
	0x6f, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x6e, 0x75, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x22, 0x4f, 0x0a, 0x11, 0x4e,
	0x65, 0x77, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x12, 0x3a, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75,
	0x64, 0x69, 0x6f, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0xf2, 0x01, 0x0a,
	0x11, 0x4e, 0x65, 0x77, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x21, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75,
	0x64, 0x69, 0x6f, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75,
	0x6d, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x22, 0x0a,
	0x0d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x71, 0x75, 0x65, 0x75, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x4d,
	0x73, 0x22, 0x4f, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e,
	0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x41,
	0x75, 0x64, 0x69, 0x6f, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x22, 0x7b, 0x0a, 0x14, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12,
	0x3e, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x42, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22,
	0x16, 0x0a, 0x14, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x13, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x23,
	0x0a, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x4e, 0x65,
	0x77, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x22, 0x5b, 0x0a, 0x14, 0x4e, 0x65, 0x77, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x09, 0x72, 0x65,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x72, 0x22,
	0xc4, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x69, 0x78, 0x41, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x72, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0f, 0x72, 0x65, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e,
	0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f,
	0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x22, 0x56, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x69, 0x78, 0x41,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x3f, 0x0a,
	0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x8b,
	0x02, 0x0a, 0x1d, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x46, 0x72,
	0x6f, 0x6d, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x2d, 0x0a, 0x12, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x5f,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x70, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12,
	0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x0b, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d,
	0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x6e, 0x75, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x22, 0x1f, 0x0a, 0x1d,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x46, 0x72, 0x6f, 0x6d, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x22, 0x53, 0x0a,
	0x12, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x12, 0x3d, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e,
	0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x52, 0x05, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x45, 0x4f, 0x53, 0x22, 0xc7, 0x01, 0x0a, 0x10, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x4d,
	0x0a, 0x0e, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e,
	0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0d,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x34, 0x0a,
	0x03, 0x65, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x2e, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x4f, 0x53, 0x48, 0x00, 0x52, 0x03,
	0x65, 0x6f, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x41,
	0x0a, 0x0f, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41,
	0x4d, 0x5f, 0x4e, 0x41, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x55,
	0x44, 0x49, 0x4f, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x48, 0x54, 0x4d, 0x4c, 0x10,
	0x01, 0x2a, 0x2a, 0x0a, 0x0f, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x5f, 0x53, 0x4f,
	0x55, 0x52, 0x43, 0x45, 0x5f, 0x4e, 0x41, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x42, 0x43, 0x5a,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x6d, 0x73, 0x64, 0x6b, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2d, 0x72, 0x74, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0xaa,
	0x02, 0x10, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x2e, 0x52, 0x54, 0x43, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_audio_proto_rawDescOnce sync.Once
	file_audio_proto_rawDescData = file_audio_proto_rawDesc
)

func file_audio_proto_rawDescGZIP() []byte {
	file_audio_proto_rawDescOnce.Do(func() {
		file_audio_proto_rawDescData = protoimpl.X.CompressGZIP(file_audio_proto_rawDescData)
	})
	return file_audio_proto_rawDescData
}

var file_audio_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_audio_proto_goTypes = []any{
	(AudioStreamType)(0),                  // 0: openim.rtc.audio.AudioStreamType
	(AudioSourceType)(0),                  // 1: openim.rtc.audio.AudioSourceType
	(*AudioStreamInfo)(nil),               // 2: openim.rtc.audio.AudioStreamInfo
	(*OwnedAudioStream)(nil),              // 3: openim.rtc.audio.OwnedAudioStream
	(*AudioSourceOptions)(nil),            // 4: openim.rtc.audio.AudioSourceOptions
	(*AudioSourceInfo)(nil),               // 5: openim.rtc.audio.AudioSourceInfo
	(*OwnedAudioSource)(nil),              // 6: openim.rtc.audio.OwnedAudioSource
	(*AudioFrameBufferInfo)(nil),          // 7: openim.rtc.audio.AudioFrameBufferInfo
	(*OwnedAudioFrameBuffer)(nil),         // 8: openim.rtc.audio.OwnedAudioFrameBuffer
	(*AudioResamplerInfo)(nil),            // 9: openim.rtc.audio.AudioResamplerInfo
	(*OwnedAudioResampler)(nil),           // 10: openim.rtc.audio.OwnedAudioResampler
	(*NewAudioStreamReq)(nil),             // 11: openim.rtc.audio.NewAudioStreamReq
	(*NewAudioStreamRes)(nil),             // 12: openim.rtc.audio.NewAudioStreamRes
	(*NewAudioSourceReq)(nil),             // 13: openim.rtc.audio.NewAudioSourceReq
	(*NewAudioSourceRes)(nil),             // 14: openim.rtc.audio.NewAudioSourceRes
	(*CaptureAudioFrameReq)(nil),          // 15: openim.rtc.audio.CaptureAudioFrameReq
	(*CaptureAudioFrameRes)(nil),          // 16: openim.rtc.audio.CaptureAudioFrameRes
	(*ClearAudioBufferReq)(nil),           // 17: openim.rtc.audio.ClearAudioBufferReq
	(*ClearAudioBufferRes)(nil),           // 18: openim.rtc.audio.ClearAudioBufferRes
	(*NewAudioResamplerReq)(nil),          // 19: openim.rtc.audio.NewAudioResamplerReq
	(*NewAudioResamplerRes)(nil),          // 20: openim.rtc.audio.NewAudioResamplerRes
	(*RemixAndResampleReq)(nil),           // 21: openim.rtc.audio.RemixAndResampleReq
	(*RemixAndResampleRes)(nil),           // 22: openim.rtc.audio.RemixAndResampleRes
	(*AudioStreamFromParticipantReq)(nil), // 23: openim.rtc.audio.AudioStreamFromParticipantReq
	(*AudioStreamFromParticipantRes)(nil), // 24: openim.rtc.audio.AudioStreamFromParticipantRes
	(*AudioFrameReceived)(nil),            // 25: openim.rtc.audio.AudioFrameReceived
	(*AudioStreamEOS)(nil),                // 26: openim.rtc.audio.AudioStreamEOS
	(*AudioStreamEvent)(nil),              // 27: openim.rtc.audio.AudioStreamEvent
	(track.TrackSource)(0),                // 28: openim.rtc.track.TrackSource
}
var file_audio_proto_depIdxs = []int32{
	0,  // 0: openim.rtc.audio.AudioStreamInfo.type:type_name -> openim.rtc.audio.AudioStreamType
	2,  // 1: openim.rtc.audio.OwnedAudioStream.info:type_name -> openim.rtc.audio.AudioStreamInfo
	1,  // 2: openim.rtc.audio.AudioSourceInfo.type:type_name -> openim.rtc.audio.AudioSourceType
	5,  // 3: openim.rtc.audio.OwnedAudioSource.info:type_name -> openim.rtc.audio.AudioSourceInfo
	7,  // 4: openim.rtc.audio.OwnedAudioFrameBuffer.info:type_name -> openim.rtc.audio.AudioFrameBufferInfo
	9,  // 5: openim.rtc.audio.OwnedAudioResampler.info:type_name -> openim.rtc.audio.AudioResamplerInfo
	0,  // 6: openim.rtc.audio.NewAudioStreamReq.type:type_name -> openim.rtc.audio.AudioStreamType
	3,  // 7: openim.rtc.audio.NewAudioStreamRes.stream:type_name -> openim.rtc.audio.OwnedAudioStream
	1,  // 8: openim.rtc.audio.NewAudioSourceReq.type:type_name -> openim.rtc.audio.AudioSourceType
	4,  // 9: openim.rtc.audio.NewAudioSourceReq.options:type_name -> openim.rtc.audio.AudioSourceOptions
	6,  // 10: openim.rtc.audio.NewAudioSourceRes.source:type_name -> openim.rtc.audio.OwnedAudioSource
	7,  // 11: openim.rtc.audio.CaptureAudioFrameReq.buffer:type_name -> openim.rtc.audio.AudioFrameBufferInfo
	10, // 12: openim.rtc.audio.NewAudioResamplerRes.resampler:type_name -> openim.rtc.audio.OwnedAudioResampler
	7,  // 13: openim.rtc.audio.RemixAndResampleReq.buffer:type_name -> openim.rtc.audio.AudioFrameBufferInfo
	8,  // 14: openim.rtc.audio.RemixAndResampleRes.buffer:type_name -> openim.rtc.audio.OwnedAudioFrameBuffer
	0,  // 15: openim.rtc.audio.AudioStreamFromParticipantReq.type:type_name -> openim.rtc.audio.AudioStreamType
	28, // 16: openim.rtc.audio.AudioStreamFromParticipantReq.track_source:type_name -> openim.rtc.track.TrackSource
	8,  // 17: openim.rtc.audio.AudioFrameReceived.frame:type_name -> openim.rtc.audio.OwnedAudioFrameBuffer
	25, // 18: openim.rtc.audio.AudioStreamEvent.frame_received:type_name -> openim.rtc.audio.AudioFrameReceived
	26, // 19: openim.rtc.audio.AudioStreamEvent.eos:type_name -> openim.rtc.audio.AudioStreamEOS
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_audio_proto_init() }
func file_audio_proto_init() {
	if File_audio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_audio_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AudioStreamInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OwnedAudioStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AudioSourceOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AudioSourceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*OwnedAudioSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AudioFrameBufferInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*OwnedAudioFrameBuffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*AudioResamplerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*OwnedAudioResampler); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*NewAudioStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*NewAudioStreamRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*NewAudioSourceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*NewAudioSourceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CaptureAudioFrameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*CaptureAudioFrameRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ClearAudioBufferReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ClearAudioBufferRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*NewAudioResamplerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*NewAudioResamplerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*RemixAndResampleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*RemixAndResampleRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*AudioStreamFromParticipantReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*AudioStreamFromParticipantRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*AudioFrameReceived); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*AudioStreamEOS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audio_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*AudioStreamEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_audio_proto_msgTypes[25].OneofWrappers = []any{
		(*AudioStreamEvent_FrameReceived)(nil),
		(*AudioStreamEvent_Eos)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_audio_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audio_proto_goTypes,
		DependencyIndexes: file_audio_proto_depIdxs,
		EnumInfos:         file_audio_proto_enumTypes,
		MessageInfos:      file_audio_proto_msgTypes,
	}.Build()
	File_audio_proto = out.File
	file_audio_proto_rawDesc = nil
	file_audio_proto_goTypes = nil
	file_audio_proto_depIdxs = nil
}
