syntax = "proto3";
package openim.rtc.audio;

option csharp_namespace = "OpenIM.RTC.Proto";
option go_package = "github.com/openimsdk/openim-rtc/proto/go/audio";

import "track.proto";

enum AudioStreamType {
  AUDIO_STREAM_NATIVE = 0;
  AUDIO_STREAM_HTML = 1;
}

enum AudioSourceType {
  AUDIO_SOURCE_NATIVE = 0;
}

message AudioStreamInfo { AudioStreamType type = 1; }

message OwnedAudioStream {
  uint64 handle = 1;
  AudioStreamInfo info = 2;
}

message AudioSourceOptions {
  bool echo_cancellation = 1;
  bool noise_suppression = 2;
  bool auto_gain_control = 3;
}

message AudioSourceInfo { AudioSourceType type = 1; }

message OwnedAudioSource {
  uint64 handle = 1;
  AudioSourceInfo info = 2;
}

message AudioFrameBufferInfo {
  uint64 data_ptr = 1; // *const i16
  uint32 num_channels = 2;
  uint32 sample_rate = 3;
  uint32 samples_per_channel = 4;
}
message OwnedAudioFrameBuffer {
  uint64 handle = 1;
  AudioFrameBufferInfo info = 2;
}

message AudioResamplerInfo {}

message OwnedAudioResampler {
  uint64 handle = 1;
  AudioResamplerInfo info = 2;
}

message NewAudioStreamReq {
  uint64 track_handle = 1;
  AudioStreamType type = 2;
  uint32 sample_rate = 3;
  uint32 num_channels = 4;
}
message NewAudioStreamRes { OwnedAudioStream stream = 1; }

message NewAudioSourceReq {
  AudioSourceType type = 1;
  AudioSourceOptions options = 2;
  uint32 sample_rate = 3;
  uint32 num_channels = 4;
  uint32 queue_size_ms = 5;
}
message NewAudioSourceRes { OwnedAudioSource source = 1; }

message CaptureAudioFrameReq {
  uint64 source_handle = 1;
  AudioFrameBufferInfo buffer = 2;
}
message CaptureAudioFrameRes {}

message ClearAudioBufferReq { uint64 source_handle = 1; }
message ClearAudioBufferRes {}

message NewAudioResamplerReq {}
message NewAudioResamplerRes { OwnedAudioResampler resampler = 1; }

message RemixAndResampleReq {
  uint64 resampler_handle = 1;
  AudioFrameBufferInfo buffer = 2;
  uint32 num_channels = 3;
  uint32 sample_rate = 4;
}
message RemixAndResampleRes { OwnedAudioFrameBuffer buffer = 1; }

message AudioStreamFromParticipantReq {
  uint64 participant_handle = 1;
  AudioStreamType type = 2;
  openim.rtc.track.TrackSource track_source = 3;
  uint32 sample_rate = 5;
  uint32 num_channels = 6;
}
message AudioStreamFromParticipantRes {}
