syntax = "proto3";
package openim.rtc.event;

option csharp_namespace = "OpenIM.RTC.Proto";
option go_package = "github.com/openimsdk/openim-rtc/proto/go/event";

import "error.proto";

enum FuncEventName {
  None = 0;
  // Room
  Connect = 1;
  Disconnect = 2;
  GetConnectState = 3;
  // Participant
  PublishTrack = 10;
  UnpublishTrack = 11;
  PublishData = 12;
  SetSubscribed = 13;
  SetLocalMetadata = 14;
  SetLocalName = 15;
  SetLocalAttributes = 16;
  PublishTranscription = 17;
  EnableRemoteTrackPublication = 18;
  UpdateRemoteTrackPublicationDimension = 19;
  SendStreamHeader = 20;
  SendStreamChunk = 21;
  SendStreamTrailer = 22;
  SetDataChannelBufferedAmountLowThreshold = 23;
  SendChatMessageRequest = 24;
  EditChatMessageRequest = 25;
  // Track
  CreateVideoTrack = 101;
  CreateAudioTrack = 102;
  LocalTrackMute = 103;
  EnableRemoteTrack = 104;
  GetStats = 105;
  SetTrackSubscriptionPermissions = 106;
  // Audio
  NewAudioStream = 201;
  NewAudioSource = 202;
  CaptureAudioFrame = 203;
  ClearAudioBuffer = 204;
  NewAudioResampler = 205;
  RemixAndResample = 206;
  AudioStreamFromParticipant = 207;
  // Video
  NewVideoStream = 301;
  NewVideoSource = 302;
  CaptureVideoFrame = 303;
  VideoConvert = 304;
  VideoStreamFromParticipan = 305;

  //   event
  RoomEvent = 1001;
  TrackEvent = 1002;
  VideoStreamEvent = 1003;
  AudioStreamEvent = 1004;
  ConnectCallback = 1005;
  DisconnectCallback = 1006;
  DisposeCallback = 1007;
  PublishTrackCallback = 1008;
  UnpublishTrackCallback = 1009;
  PublishDataCallback = 1010;
  PublishTranscriptionCallback = 1011;
  CaptureAudioFrameCallback = 1012;
  SetLocalMetadataCallback = 1013;
  SetLocalNameCallback = 1014;
  SetLocalAttributesCallback = 1015;
  GetStatsCallback = 1016;
  LogBatch = 1017;
  GetSessionStatsCallback = 1018;
  Panic = 1019;
  PublishSipDtmfCallback = 1020;
  SendChatMessageCallback = 1021;
  PerformRpcCallback = 1022;
  RpcMethodInvocationEvent = 1023;
  SendStreamHeaderCallback = 1024;
  SendStreamChunkCallback = 1025;
  SendStreamTrailerCallback = 1026;
}

message FfiRequest {
  // note: This field is optional and is only used for interaction between Go
  // and JS.
  string operationId = 1;
  // The handle Id.
  int64 handleId = 2;
  // Function request event name.
  FuncEventName eventName = 3;
  // The request data.
  bytes data = 4;
}

message FfiResult {
  openim.rtc.error.ErrCode errCode = 1;
  string errMsg = 2;
  FuncEventName eventName = 3;
  // The result data.
  bytes data = 4;
  // handleId
  int64 handleId = 5;
}