syntax = "proto3";
package openim.rtc.ffi;

option csharp_namespace = "OpenIM.RTC.Proto";
option go_package = "github.com/openimsdk/openim-rtc/proto/go/ffi";

enum FuncRequestEventName {
  None = 0;
  // Room
  Connect = 1;
  Disconnect = 2;
  PublishTrack = 3;
  UnpublishTrack = 4;
  PublishData = 5;
  SetSubscribed = 6;
  SetLocalMetadata = 7;
  SetLocalName = 8;
  SetLocalAttributes = 9;
  GetSessionStats = 10;
  PublishTranscription = 11;
  PublishSipDtmf = 12;
  EnableRemoteTrackPublication = 42;
  UpdateRemoteTrackPublicationDimension = 43;
  SendStreamHeader = 44;
  SendStreamChunk = 45;
  SendStreamTrailer = 46;
  SetDataChannelBufferedAmountLowThreshold = 47;

  // Track
  CreateVideoTrack = 101;
  CreateAudioTrack = 102;
  LocalTrackMute = 103;
  EnableRemoteTrack = 104;
  GetStats = 105;
  SetTrackSubscriptionPermissions = 106;

  // Video
  NewVideoStream = 201;
  NewVideoSource = 202;
  CaptureVideoFrame = 203;
  VideoConvert = 204;
  VideoStreamFromParticipan = 205;

  // Audio
  NewAudioStream = 301;
  NewAudioSource = 302;
  CaptureAudioFrame = 303;
  ClearAudioBuffer = 304;
  NewAudioResampler = 305;
  RemixAndResample = 306;
  AudioStreamFromParticipant = 307;
  NewSoxResampler = 308;
  PushSoxResampler = 309;
  FlushSoxResampler = 310;
  SendChatMessage = 311;
  EditChatMessage = 312;
}