syntax = "proto3";
package openim.rtc.room;

option csharp_namespace = "OpenIM.RTC.Proto";
option go_package = "github.com/openimsdk/openim-rtc/proto/go/room";

import "common.proto";
import "participant.proto";
import "track.proto";

message BufferInfo {
  uint64 data_ptr = 1;
  uint64 data_len = 2;
}

message OwnedBuffer {
  uint64 handle = 1;
  BufferInfo data = 2;
}

message UserPacket {
  string topic = 1;
  bytes data = 2;
}

message ChatMessageReceived {
  openim.rtc.participant.ChatMessage message = 1;
  string participant_identity = 2;
}

message SipDTMF {
  uint32 code = 1;
  string digit = 2;
}

message RoomOptions {
  bool auto_subscribe = 1;
  bool adaptive_stream = 2;
  bool dynacast = 3;
}

message ConnectReq {
  string url = 1;
  string token = 2;
  RoomOptions options = 3;
}
message ConnectRes {
  uint64 room_handle = 1;
  uint64 local_participant_handle = 2;
}

message DisconnectReq { uint64 room_handle = 1; }
message DisconnectRes {}

message GetConnectStateReq { uint64 room_handle = 1; }
message GetConnectStateRes { openim.rtc.common.ConnectionState state = 1; }

message ParticipantConnected {
  openim.rtc.participant.OwnedParticipant info = 1;
}

message ParticipantDisconnected { string participant_identity = 1; }

message LocalTrackPublished { string track_sid = 1; }

message LocalTrackUnpublished { string publication_sid = 1; }

message LocalTrackSubscribed { string track_sid = 1; }

message TrackPublished {
  string participant_identity = 1;
  openim.rtc.track.TrackPublicationInfo publication = 2;
}

message TrackUnpublished {
  string participant_identity = 1;
  string publication_sid = 2;
}

message TrackSubscribed {
  string participant_identity = 1;
  openim.rtc.track.TrackInfo track = 2;
}

message TrackUnsubscribed {
  string participant_identity = 1;
  string track_sid = 2;
}

message TrackSubscriptionFailed {
  string participant_identity = 1;
  string track_sid = 2;
  string error = 3;
}

message TrackMuted {
  string participant_identity = 1;
  string track_sid = 2;
}

message TrackUnmuted {
  string participant_identity = 1;
  string track_sid = 2;
}

message ActiveSpeakersChanged { repeated string participant_identities = 1; }

message RoomMetadataChanged { string metadata = 1; }

message RoomSidChanged { string sid = 1; }

message ParticipantMetadataChanged {
  string participant_identity = 1;
  string metadata = 2;
}

message ParticipantNameChanged {
  string participant_identity = 1;
  string name = 2;
}

message ParticipantAttributesChanged {
  string participant_identity = 1;
  repeated openim.rtc.common.AttributesEntry attributes = 2;
  repeated openim.rtc.common.AttributesEntry changed_attributes = 3;
}
message ConnectionQualityChanged {
  string participant_identity = 1;
  openim.rtc.common.ConnectionQuality quality = 2;
}

message ConnectionStateChanged { openim.rtc.common.ConnectionState state = 1; }

message Disconnected { openim.rtc.common.DisconnectReason reason = 1; }

message Reconnecting {}

message Reconnected {}

message DataPacketReceived {
  openim.rtc.common.DataPacketKind kind = 1;
  // Can be empty if the data is sent a server SDK
  string participant_identity = 2;
  oneof value {
    UserPacket user = 4;
    SipDTMF sip_dtmf = 5;
  }
}

message TranscriptionReceived {
  string participant_identity = 1;
  string track_sid = 2;
  repeated openim.rtc.participant.TranscriptionSegment segments = 3;
}

message RoomEvent {
  uint64 room_handle = 1;
  oneof message {
    ParticipantConnected participant_connected = 2;
    ParticipantDisconnected participant_disconnected = 3;
    LocalTrackPublished local_track_published = 4;
    LocalTrackUnpublished local_track_unpublished = 5;
    LocalTrackSubscribed local_track_subscribed = 6;
    TrackPublished track_published = 7;
    TrackUnpublished track_unpublished = 8;
    TrackSubscribed track_subscribed = 9;
    TrackUnsubscribed track_unsubscribed = 10;
    TrackSubscriptionFailed track_subscription_failed = 11;
    TrackMuted track_muted = 12;
    TrackUnmuted track_unmuted = 13;
    ActiveSpeakersChanged active_speakers_changed = 14;
    RoomMetadataChanged room_metadata_changed = 15;
    RoomSidChanged room_sid_changed = 16;
    ParticipantMetadataChanged participant_metadata_changed = 17;
    ParticipantNameChanged participant_name_changed = 18;
    ParticipantAttributesChanged participant_attributes_changed = 19;
    ConnectionQualityChanged connection_quality_changed = 20;
    ConnectionStateChanged connection_state_changed = 21;
    Disconnected disconnected = 22;
    Reconnecting reconnecting = 23;
    Reconnected reconnected = 24;
    DataPacketReceived data_packet_received = 27;
    TranscriptionReceived transcription_received = 28;
  }
}