syntax = "proto3";
package openim.rtc.room;

option csharp_namespace = "OpenIM.RTC.Proto";
option go_package = "github.com/openimsdk/openim-rtc/proto/go/room";

message RoomOptions {
  bool auto_subscribe = 1;  // 自动订阅
  bool adaptive_stream = 2; // 自适应码流
  bool dynacast = 3;        // 动态广播
}

message ConnectReq {
  string url = 1;
  string token = 2;
  RoomOptions options = 3;
}
message ConnectRes {
  uint64 room_handle=1;
  uint64 local_participant_handle = 2;
}

message DisconnectReq { uint64 room_handle = 1; }
message DisconnectRes {}