// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.27.1
// source: track.proto

package track

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackKind int32

const (
	TrackKind_KIND_UNKNOWN TrackKind = 0
	TrackKind_KIND_AUDIO   TrackKind = 1
	TrackKind_KIND_VIDEO   TrackKind = 2
)

// Enum value maps for TrackKind.
var (
	TrackKind_name = map[int32]string{
		0: "KIND_UNKNOWN",
		1: "KIND_AUDIO",
		2: "KIND_VIDEO",
	}
	TrackKind_value = map[string]int32{
		"KIND_UNKNOWN": 0,
		"KIND_AUDIO":   1,
		"KIND_VIDEO":   2,
	}
)

func (x TrackKind) Enum() *TrackKind {
	p := new(TrackKind)
	*p = x
	return p
}

func (x TrackKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackKind) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[0].Descriptor()
}

func (TrackKind) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[0]
}

func (x TrackKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackKind.Descriptor instead.
func (TrackKind) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{0}
}

type TrackSource int32

const (
	TrackSource_SOURCE_UNKNOWN           TrackSource = 0
	TrackSource_SOURCE_CAMERA            TrackSource = 1
	TrackSource_SOURCE_MICROPHONE        TrackSource = 2
	TrackSource_SOURCE_SCREENSHARE       TrackSource = 3
	TrackSource_SOURCE_SCREENSHARE_AUDIO TrackSource = 4
)

// Enum value maps for TrackSource.
var (
	TrackSource_name = map[int32]string{
		0: "SOURCE_UNKNOWN",
		1: "SOURCE_CAMERA",
		2: "SOURCE_MICROPHONE",
		3: "SOURCE_SCREENSHARE",
		4: "SOURCE_SCREENSHARE_AUDIO",
	}
	TrackSource_value = map[string]int32{
		"SOURCE_UNKNOWN":           0,
		"SOURCE_CAMERA":            1,
		"SOURCE_MICROPHONE":        2,
		"SOURCE_SCREENSHARE":       3,
		"SOURCE_SCREENSHARE_AUDIO": 4,
	}
)

func (x TrackSource) Enum() *TrackSource {
	p := new(TrackSource)
	*p = x
	return p
}

func (x TrackSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackSource) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[1].Descriptor()
}

func (TrackSource) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[1]
}

func (x TrackSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackSource.Descriptor instead.
func (TrackSource) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{1}
}

type StreamState int32

const (
	StreamState_STATE_UNKNOWN StreamState = 0
	StreamState_STATE_ACTIVE  StreamState = 1
	StreamState_STATE_PAUSED  StreamState = 2
)

// Enum value maps for StreamState.
var (
	StreamState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "STATE_ACTIVE",
		2: "STATE_PAUSED",
	}
	StreamState_value = map[string]int32{
		"STATE_UNKNOWN": 0,
		"STATE_ACTIVE":  1,
		"STATE_PAUSED":  2,
	}
)

func (x StreamState) Enum() *StreamState {
	p := new(StreamState)
	*p = x
	return p
}

func (x StreamState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamState) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[2].Descriptor()
}

func (StreamState) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[2]
}

func (x StreamState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamState.Descriptor instead.
func (StreamState) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{2}
}

type TrackEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEvent) Reset() {
	*x = TrackEvent{}
	mi := &file_track_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEvent) ProtoMessage() {}

func (x *TrackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEvent.ProtoReflect.Descriptor instead.
func (*TrackEvent) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{0}
}

type TrackPublicationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Kind          TrackKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=openim.rtc.track.TrackKind" json:"kind"`
	Source        TrackSource            `protobuf:"varint,4,opt,name=source,proto3,enum=openim.rtc.track.TrackSource" json:"source"`
	Simulcasted   bool                   `protobuf:"varint,5,opt,name=simulcasted,proto3" json:"simulcasted"`
	Width         uint32                 `protobuf:"varint,6,opt,name=width,proto3" json:"width"`
	Height        uint32                 `protobuf:"varint,7,opt,name=height,proto3" json:"height"`
	MimeType      string                 `protobuf:"bytes,8,opt,name=mime_type,json=mimeType,proto3" json:"mime_type"`
	Muted         bool                   `protobuf:"varint,9,opt,name=muted,proto3" json:"muted"`
	Remote        bool                   `protobuf:"varint,10,opt,name=remote,proto3" json:"remote"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackPublicationInfo) Reset() {
	*x = TrackPublicationInfo{}
	mi := &file_track_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackPublicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPublicationInfo) ProtoMessage() {}

func (x *TrackPublicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPublicationInfo.ProtoReflect.Descriptor instead.
func (*TrackPublicationInfo) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{1}
}

func (x *TrackPublicationInfo) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *TrackPublicationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrackPublicationInfo) GetKind() TrackKind {
	if x != nil {
		return x.Kind
	}
	return TrackKind_KIND_UNKNOWN
}

func (x *TrackPublicationInfo) GetSource() TrackSource {
	if x != nil {
		return x.Source
	}
	return TrackSource_SOURCE_UNKNOWN
}

func (x *TrackPublicationInfo) GetSimulcasted() bool {
	if x != nil {
		return x.Simulcasted
	}
	return false
}

func (x *TrackPublicationInfo) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TrackPublicationInfo) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TrackPublicationInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *TrackPublicationInfo) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *TrackPublicationInfo) GetRemote() bool {
	if x != nil {
		return x.Remote
	}
	return false
}

type OwnedTrackPublication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint64                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle"`
	Info          *TrackPublicationInfo  `protobuf:"bytes,2,opt,name=info,proto3" json:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedTrackPublication) Reset() {
	*x = OwnedTrackPublication{}
	mi := &file_track_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedTrackPublication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedTrackPublication) ProtoMessage() {}

func (x *OwnedTrackPublication) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedTrackPublication.ProtoReflect.Descriptor instead.
func (*OwnedTrackPublication) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{2}
}

func (x *OwnedTrackPublication) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *OwnedTrackPublication) GetInfo() *TrackPublicationInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type TrackInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Kind          TrackKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=openim.rtc.track.TrackKind" json:"kind"`
	StreamState   StreamState            `protobuf:"varint,4,opt,name=stream_state,json=streamState,proto3,enum=openim.rtc.track.StreamState" json:"stream_state"`
	Muted         bool                   `protobuf:"varint,5,opt,name=muted,proto3" json:"muted"`
	Remote        bool                   `protobuf:"varint,6,opt,name=remote,proto3" json:"remote"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackInfo) Reset() {
	*x = TrackInfo{}
	mi := &file_track_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfo) ProtoMessage() {}

func (x *TrackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfo.ProtoReflect.Descriptor instead.
func (*TrackInfo) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{3}
}

func (x *TrackInfo) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *TrackInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrackInfo) GetKind() TrackKind {
	if x != nil {
		return x.Kind
	}
	return TrackKind_KIND_UNKNOWN
}

func (x *TrackInfo) GetStreamState() StreamState {
	if x != nil {
		return x.StreamState
	}
	return StreamState_STATE_UNKNOWN
}

func (x *TrackInfo) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *TrackInfo) GetRemote() bool {
	if x != nil {
		return x.Remote
	}
	return false
}

type OwnedTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        uint64                 `protobuf:"varint,1,opt,name=handle,proto3" json:"handle"`
	Info          *TrackInfo             `protobuf:"bytes,2,opt,name=info,proto3" json:"info"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OwnedTrack) Reset() {
	*x = OwnedTrack{}
	mi := &file_track_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OwnedTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedTrack) ProtoMessage() {}

func (x *OwnedTrack) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedTrack.ProtoReflect.Descriptor instead.
func (*OwnedTrack) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{4}
}

func (x *OwnedTrack) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

func (x *OwnedTrack) GetInfo() *TrackInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ParticipantTrackPermission struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ParticipantIdentity string                 `protobuf:"bytes,1,opt,name=participant_identity,json=participantIdentity,proto3" json:"participant_identity"`
	AllowAll            bool                   `protobuf:"varint,2,opt,name=allow_all,json=allowAll,proto3" json:"allow_all"`
	AllowedTrackSids    string                 `protobuf:"bytes,3,opt,name=allowed_track_sids,json=allowedTrackSids,proto3" json:"allowed_track_sids"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ParticipantTrackPermission) Reset() {
	*x = ParticipantTrackPermission{}
	mi := &file_track_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantTrackPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantTrackPermission) ProtoMessage() {}

func (x *ParticipantTrackPermission) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantTrackPermission.ProtoReflect.Descriptor instead.
func (*ParticipantTrackPermission) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{5}
}

func (x *ParticipantTrackPermission) GetParticipantIdentity() string {
	if x != nil {
		return x.ParticipantIdentity
	}
	return ""
}

func (x *ParticipantTrackPermission) GetAllowAll() bool {
	if x != nil {
		return x.AllowAll
	}
	return false
}

func (x *ParticipantTrackPermission) GetAllowedTrackSids() string {
	if x != nil {
		return x.AllowedTrackSids
	}
	return ""
}

type CreateVideoTrackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	SourceHandle  uint64                 `protobuf:"varint,2,opt,name=source_handle,json=sourceHandle,proto3" json:"source_handle"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoTrackReq) Reset() {
	*x = CreateVideoTrackReq{}
	mi := &file_track_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoTrackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoTrackReq) ProtoMessage() {}

func (x *CreateVideoTrackReq) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoTrackReq.ProtoReflect.Descriptor instead.
func (*CreateVideoTrackReq) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{6}
}

func (x *CreateVideoTrackReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVideoTrackReq) GetSourceHandle() uint64 {
	if x != nil {
		return x.SourceHandle
	}
	return 0
}

type CreateVideoTrackRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *OwnedTrack            `protobuf:"bytes,1,opt,name=track,proto3" json:"track"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoTrackRes) Reset() {
	*x = CreateVideoTrackRes{}
	mi := &file_track_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoTrackRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoTrackRes) ProtoMessage() {}

func (x *CreateVideoTrackRes) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoTrackRes.ProtoReflect.Descriptor instead.
func (*CreateVideoTrackRes) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVideoTrackRes) GetTrack() *OwnedTrack {
	if x != nil {
		return x.Track
	}
	return nil
}

type CreateAudioTrackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	SourceHandle  uint64                 `protobuf:"varint,2,opt,name=source_handle,json=sourceHandle,proto3" json:"source_handle"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAudioTrackReq) Reset() {
	*x = CreateAudioTrackReq{}
	mi := &file_track_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAudioTrackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudioTrackReq) ProtoMessage() {}

func (x *CreateAudioTrackReq) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudioTrackReq.ProtoReflect.Descriptor instead.
func (*CreateAudioTrackReq) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAudioTrackReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAudioTrackReq) GetSourceHandle() uint64 {
	if x != nil {
		return x.SourceHandle
	}
	return 0
}

type CreateAudioTrackRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *OwnedTrack            `protobuf:"bytes,1,opt,name=track,proto3" json:"track"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAudioTrackRes) Reset() {
	*x = CreateAudioTrackRes{}
	mi := &file_track_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAudioTrackRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudioTrackRes) ProtoMessage() {}

func (x *CreateAudioTrackRes) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudioTrackRes.ProtoReflect.Descriptor instead.
func (*CreateAudioTrackRes) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAudioTrackRes) GetTrack() *OwnedTrack {
	if x != nil {
		return x.Track
	}
	return nil
}

type LocalTrackMuteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackHandle   uint64                 `protobuf:"varint,1,opt,name=track_handle,json=trackHandle,proto3" json:"track_handle"`
	Mute          bool                   `protobuf:"varint,2,opt,name=mute,proto3" json:"mute"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalTrackMuteReq) Reset() {
	*x = LocalTrackMuteReq{}
	mi := &file_track_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalTrackMuteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalTrackMuteReq) ProtoMessage() {}

func (x *LocalTrackMuteReq) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalTrackMuteReq.ProtoReflect.Descriptor instead.
func (*LocalTrackMuteReq) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{10}
}

func (x *LocalTrackMuteReq) GetTrackHandle() uint64 {
	if x != nil {
		return x.TrackHandle
	}
	return 0
}

func (x *LocalTrackMuteReq) GetMute() bool {
	if x != nil {
		return x.Mute
	}
	return false
}

type LocalTrackMuteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Muted         bool                   `protobuf:"varint,1,opt,name=muted,proto3" json:"muted"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalTrackMuteRes) Reset() {
	*x = LocalTrackMuteRes{}
	mi := &file_track_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalTrackMuteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalTrackMuteRes) ProtoMessage() {}

func (x *LocalTrackMuteRes) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalTrackMuteRes.ProtoReflect.Descriptor instead.
func (*LocalTrackMuteRes) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{11}
}

func (x *LocalTrackMuteRes) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

type EnableRemoteTrackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackHandle   uint64                 `protobuf:"varint,1,opt,name=track_handle,json=trackHandle,proto3" json:"track_handle"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRemoteTrackReq) Reset() {
	*x = EnableRemoteTrackReq{}
	mi := &file_track_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRemoteTrackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRemoteTrackReq) ProtoMessage() {}

func (x *EnableRemoteTrackReq) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRemoteTrackReq.ProtoReflect.Descriptor instead.
func (*EnableRemoteTrackReq) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{12}
}

func (x *EnableRemoteTrackReq) GetTrackHandle() uint64 {
	if x != nil {
		return x.TrackHandle
	}
	return 0
}

func (x *EnableRemoteTrackReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type EnableRemoteTrackRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableRemoteTrackRes) Reset() {
	*x = EnableRemoteTrackRes{}
	mi := &file_track_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableRemoteTrackRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRemoteTrackRes) ProtoMessage() {}

func (x *EnableRemoteTrackRes) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRemoteTrackRes.ProtoReflect.Descriptor instead.
func (*EnableRemoteTrackRes) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{13}
}

func (x *EnableRemoteTrackRes) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetTrackSubscriptionPermissionsReq struct {
	state                  protoimpl.MessageState      `protogen:"open.v1"`
	LocalParticipantHandle uint64                      `protobuf:"varint,1,opt,name=local_participant_handle,json=localParticipantHandle,proto3" json:"local_participant_handle"`
	AllParticipantsAllowed bool                        `protobuf:"varint,2,opt,name=all_participants_allowed,json=allParticipantsAllowed,proto3" json:"all_participants_allowed"`
	Permissions            *ParticipantTrackPermission `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetTrackSubscriptionPermissionsReq) Reset() {
	*x = SetTrackSubscriptionPermissionsReq{}
	mi := &file_track_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTrackSubscriptionPermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTrackSubscriptionPermissionsReq) ProtoMessage() {}

func (x *SetTrackSubscriptionPermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTrackSubscriptionPermissionsReq.ProtoReflect.Descriptor instead.
func (*SetTrackSubscriptionPermissionsReq) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{14}
}

func (x *SetTrackSubscriptionPermissionsReq) GetLocalParticipantHandle() uint64 {
	if x != nil {
		return x.LocalParticipantHandle
	}
	return 0
}

func (x *SetTrackSubscriptionPermissionsReq) GetAllParticipantsAllowed() bool {
	if x != nil {
		return x.AllParticipantsAllowed
	}
	return false
}

func (x *SetTrackSubscriptionPermissionsReq) GetPermissions() *ParticipantTrackPermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type SetTrackSubscriptionPermissionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTrackSubscriptionPermissionsRes) Reset() {
	*x = SetTrackSubscriptionPermissionsRes{}
	mi := &file_track_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTrackSubscriptionPermissionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTrackSubscriptionPermissionsRes) ProtoMessage() {}

func (x *SetTrackSubscriptionPermissionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTrackSubscriptionPermissionsRes.ProtoReflect.Descriptor instead.
func (*SetTrackSubscriptionPermissionsRes) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{15}
}

var File_track_proto protoreflect.FileDescriptor

var file_track_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x22,
	0x0c, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xbf, 0x02,
	0x0a, 0x14, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x35, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x63, 0x61, 0x73,
	0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x69, 0x6d, 0x75, 0x6c,
	0x63, 0x61, 0x73, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x22,
	0x6b, 0x0a, 0x15, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x12, 0x3a, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xd2, 0x01, 0x0a,
	0x09, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x2f, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b,
	0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x40, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d,
	0x2e, 0x72, 0x74, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x22, 0x55, 0x0a, 0x0a, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72,
	0x74, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x9a, 0x01, 0x0a, 0x1a, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x14, 0x70, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x73, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x53, 0x69, 0x64, 0x73, 0x22, 0x4e, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x49, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x05,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x70,
	0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x4f,
	0x77, 0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x22, 0x4e, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x22, 0x49, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e,
	0x72, 0x74, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x22, 0x4a, 0x0a, 0x11, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4d, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x6d, 0x75, 0x74, 0x65, 0x22, 0x29, 0x0a, 0x11, 0x4c, 0x6f, 0x63, 0x61, 0x6c,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x4d, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d, 0x75, 0x74,
	0x65, 0x64, 0x22, 0x53, 0x0a, 0x14, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0xe8, 0x01, 0x0a, 0x22, 0x53, 0x65,
	0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x38, 0x0a, 0x18, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x69, 0x70, 0x61, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x16, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69,
	0x70, 0x61, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x18, 0x61, 0x6c,
	0x6c, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x5f, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x61, 0x6c,
	0x6c, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x41, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x12, 0x4e, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x24, 0x0a, 0x22, 0x53, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x2a, 0x3d, 0x0a, 0x09, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x0c, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x02, 0x2a, 0x81, 0x01, 0x0a, 0x0b, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x4f, 0x55,
	0x52, 0x43, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x43, 0x41, 0x4d, 0x45, 0x52, 0x41, 0x10, 0x01,
	0x12, 0x15, 0x0a, 0x11, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x4d, 0x49, 0x43, 0x52, 0x4f,
	0x50, 0x48, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x4f, 0x55, 0x52, 0x43,
	0x45, 0x5f, 0x53, 0x43, 0x52, 0x45, 0x45, 0x4e, 0x53, 0x48, 0x41, 0x52, 0x45, 0x10, 0x03, 0x12,
	0x1c, 0x0a, 0x18, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x53, 0x43, 0x52, 0x45, 0x45, 0x4e,
	0x53, 0x48, 0x41, 0x52, 0x45, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x04, 0x2a, 0x44, 0x0a,
	0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x11, 0x0a, 0x0d,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10,
	0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x41, 0x55, 0x53, 0x45,
	0x44, 0x10, 0x02, 0x42, 0x43, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x73, 0x64, 0x6b, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x6d, 0x2d, 0x72, 0x74, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0xaa, 0x02, 0x10, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x4d, 0x2e, 0x52,
	0x54, 0x43, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_track_proto_rawDescOnce sync.Once
	file_track_proto_rawDescData = file_track_proto_rawDesc
)

func file_track_proto_rawDescGZIP() []byte {
	file_track_proto_rawDescOnce.Do(func() {
		file_track_proto_rawDescData = protoimpl.X.CompressGZIP(file_track_proto_rawDescData)
	})
	return file_track_proto_rawDescData
}

var file_track_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_track_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_track_proto_goTypes = []any{
	(TrackKind)(0),                             // 0: openim.rtc.track.TrackKind
	(TrackSource)(0),                           // 1: openim.rtc.track.TrackSource
	(StreamState)(0),                           // 2: openim.rtc.track.StreamState
	(*TrackEvent)(nil),                         // 3: openim.rtc.track.TrackEvent
	(*TrackPublicationInfo)(nil),               // 4: openim.rtc.track.TrackPublicationInfo
	(*OwnedTrackPublication)(nil),              // 5: openim.rtc.track.OwnedTrackPublication
	(*TrackInfo)(nil),                          // 6: openim.rtc.track.TrackInfo
	(*OwnedTrack)(nil),                         // 7: openim.rtc.track.OwnedTrack
	(*ParticipantTrackPermission)(nil),         // 8: openim.rtc.track.ParticipantTrackPermission
	(*CreateVideoTrackReq)(nil),                // 9: openim.rtc.track.CreateVideoTrackReq
	(*CreateVideoTrackRes)(nil),                // 10: openim.rtc.track.CreateVideoTrackRes
	(*CreateAudioTrackReq)(nil),                // 11: openim.rtc.track.CreateAudioTrackReq
	(*CreateAudioTrackRes)(nil),                // 12: openim.rtc.track.CreateAudioTrackRes
	(*LocalTrackMuteReq)(nil),                  // 13: openim.rtc.track.LocalTrackMuteReq
	(*LocalTrackMuteRes)(nil),                  // 14: openim.rtc.track.LocalTrackMuteRes
	(*EnableRemoteTrackReq)(nil),               // 15: openim.rtc.track.EnableRemoteTrackReq
	(*EnableRemoteTrackRes)(nil),               // 16: openim.rtc.track.EnableRemoteTrackRes
	(*SetTrackSubscriptionPermissionsReq)(nil), // 17: openim.rtc.track.SetTrackSubscriptionPermissionsReq
	(*SetTrackSubscriptionPermissionsRes)(nil), // 18: openim.rtc.track.SetTrackSubscriptionPermissionsRes
}
var file_track_proto_depIdxs = []int32{
	0, // 0: openim.rtc.track.TrackPublicationInfo.kind:type_name -> openim.rtc.track.TrackKind
	1, // 1: openim.rtc.track.TrackPublicationInfo.source:type_name -> openim.rtc.track.TrackSource
	4, // 2: openim.rtc.track.OwnedTrackPublication.info:type_name -> openim.rtc.track.TrackPublicationInfo
	0, // 3: openim.rtc.track.TrackInfo.kind:type_name -> openim.rtc.track.TrackKind
	2, // 4: openim.rtc.track.TrackInfo.stream_state:type_name -> openim.rtc.track.StreamState
	6, // 5: openim.rtc.track.OwnedTrack.info:type_name -> openim.rtc.track.TrackInfo
	7, // 6: openim.rtc.track.CreateVideoTrackRes.track:type_name -> openim.rtc.track.OwnedTrack
	7, // 7: openim.rtc.track.CreateAudioTrackRes.track:type_name -> openim.rtc.track.OwnedTrack
	8, // 8: openim.rtc.track.SetTrackSubscriptionPermissionsReq.permissions:type_name -> openim.rtc.track.ParticipantTrackPermission
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_track_proto_init() }
func file_track_proto_init() {
	if File_track_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_track_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_track_proto_goTypes,
		DependencyIndexes: file_track_proto_depIdxs,
		EnumInfos:         file_track_proto_enumTypes,
		MessageInfos:      file_track_proto_msgTypes,
	}.Build()
	File_track_proto = out.File
	file_track_proto_rawDesc = nil
	file_track_proto_goTypes = nil
	file_track_proto_depIdxs = nil
}
