// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2-devel
// 	protoc        v4.25.1
// source: track.proto

package track

import (
	e2ee "github.com/openimsdk/openim-rtc/proto/go/e2ee"
	handle "github.com/openimsdk/openim-rtc/proto/go/handle"
	stats "github.com/openimsdk/openim-rtc/proto/go/stats"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackKind int32

const (
	TrackKind_KIND_UNKNOWN TrackKind = 0
	TrackKind_KIND_AUDIO   TrackKind = 1
	TrackKind_KIND_VIDEO   TrackKind = 2
)

// Enum value maps for TrackKind.
var (
	TrackKind_name = map[int32]string{
		0: "KIND_UNKNOWN",
		1: "KIND_AUDIO",
		2: "KIND_VIDEO",
	}
	TrackKind_value = map[string]int32{
		"KIND_UNKNOWN": 0,
		"KIND_AUDIO":   1,
		"KIND_VIDEO":   2,
	}
)

func (x TrackKind) Enum() *TrackKind {
	p := new(TrackKind)
	*p = x
	return p
}

func (x TrackKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackKind) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[0].Descriptor()
}

func (TrackKind) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[0]
}

func (x TrackKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackKind.Descriptor instead.
func (TrackKind) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{0}
}

type TrackSource int32

const (
	TrackSource_SOURCE_UNKNOWN           TrackSource = 0
	TrackSource_SOURCE_CAMERA            TrackSource = 1
	TrackSource_SOURCE_MICROPHONE        TrackSource = 2
	TrackSource_SOURCE_SCREENSHARE       TrackSource = 3
	TrackSource_SOURCE_SCREENSHARE_AUDIO TrackSource = 4
)

// Enum value maps for TrackSource.
var (
	TrackSource_name = map[int32]string{
		0: "SOURCE_UNKNOWN",
		1: "SOURCE_CAMERA",
		2: "SOURCE_MICROPHONE",
		3: "SOURCE_SCREENSHARE",
		4: "SOURCE_SCREENSHARE_AUDIO",
	}
	TrackSource_value = map[string]int32{
		"SOURCE_UNKNOWN":           0,
		"SOURCE_CAMERA":            1,
		"SOURCE_MICROPHONE":        2,
		"SOURCE_SCREENSHARE":       3,
		"SOURCE_SCREENSHARE_AUDIO": 4,
	}
)

func (x TrackSource) Enum() *TrackSource {
	p := new(TrackSource)
	*p = x
	return p
}

func (x TrackSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackSource) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[1].Descriptor()
}

func (TrackSource) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[1]
}

func (x TrackSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrackSource.Descriptor instead.
func (TrackSource) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{1}
}

type StreamState int32

const (
	StreamState_STATE_UNKNOWN StreamState = 0
	StreamState_STATE_ACTIVE  StreamState = 1
	StreamState_STATE_PAUSED  StreamState = 2
)

// Enum value maps for StreamState.
var (
	StreamState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "STATE_ACTIVE",
		2: "STATE_PAUSED",
	}
	StreamState_value = map[string]int32{
		"STATE_UNKNOWN": 0,
		"STATE_ACTIVE":  1,
		"STATE_PAUSED":  2,
	}
)

func (x StreamState) Enum() *StreamState {
	p := new(StreamState)
	*p = x
	return p
}

func (x StreamState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamState) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[2].Descriptor()
}

func (StreamState) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[2]
}

func (x StreamState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamState.Descriptor instead.
func (StreamState) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{2}
}

// Create a new VideoTrack from a VideoSource
type CreateVideoTrackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	SourceHandle uint64 `protobuf:"varint,2,opt,name=source_handle,json=sourceHandle,proto3" json:"source_handle"`
}

func (x *CreateVideoTrackRequest) Reset() {
	*x = CreateVideoTrackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVideoTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoTrackRequest) ProtoMessage() {}

func (x *CreateVideoTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoTrackRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVideoTrackRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVideoTrackRequest) GetSourceHandle() uint64 {
	if x != nil {
		return x.SourceHandle
	}
	return 0
}

type CreateVideoTrackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Track *OwnedTrack `protobuf:"bytes,1,opt,name=track,proto3" json:"track"`
}

func (x *CreateVideoTrackResponse) Reset() {
	*x = CreateVideoTrackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVideoTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoTrackResponse) ProtoMessage() {}

func (x *CreateVideoTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoTrackResponse.ProtoReflect.Descriptor instead.
func (*CreateVideoTrackResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVideoTrackResponse) GetTrack() *OwnedTrack {
	if x != nil {
		return x.Track
	}
	return nil
}

// Create a new AudioTrack from a AudioSource
type CreateAudioTrackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	SourceHandle uint64 `protobuf:"varint,2,opt,name=source_handle,json=sourceHandle,proto3" json:"source_handle"`
}

func (x *CreateAudioTrackRequest) Reset() {
	*x = CreateAudioTrackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAudioTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudioTrackRequest) ProtoMessage() {}

func (x *CreateAudioTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudioTrackRequest.ProtoReflect.Descriptor instead.
func (*CreateAudioTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAudioTrackRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAudioTrackRequest) GetSourceHandle() uint64 {
	if x != nil {
		return x.SourceHandle
	}
	return 0
}

type CreateAudioTrackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Track *OwnedTrack `protobuf:"bytes,1,opt,name=track,proto3" json:"track"`
}

func (x *CreateAudioTrackResponse) Reset() {
	*x = CreateAudioTrackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAudioTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudioTrackResponse) ProtoMessage() {}

func (x *CreateAudioTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudioTrackResponse.ProtoReflect.Descriptor instead.
func (*CreateAudioTrackResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAudioTrackResponse) GetTrack() *OwnedTrack {
	if x != nil {
		return x.Track
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackHandle uint64 `protobuf:"varint,1,opt,name=track_handle,json=trackHandle,proto3" json:"track_handle"`
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatsRequest) GetTrackHandle() uint64 {
	if x != nil {
		return x.TrackHandle
	}
	return 0
}

type GetStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AsyncId uint64 `protobuf:"varint,1,opt,name=async_id,json=asyncId,proto3" json:"async_id"`
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatsResponse) GetAsyncId() uint64 {
	if x != nil {
		return x.AsyncId
	}
	return 0
}

type GetStatsCallback struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AsyncId uint64            `protobuf:"varint,1,opt,name=async_id,json=asyncId,proto3" json:"async_id"`
	Error   string            `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
	Stats   []*stats.RtcStats `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats"`
}

func (x *GetStatsCallback) Reset() {
	*x = GetStatsCallback{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsCallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsCallback) ProtoMessage() {}

func (x *GetStatsCallback) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsCallback.ProtoReflect.Descriptor instead.
func (*GetStatsCallback) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatsCallback) GetAsyncId() uint64 {
	if x != nil {
		return x.AsyncId
	}
	return 0
}

func (x *GetStatsCallback) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetStatsCallback) GetStats() []*stats.RtcStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type TrackEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackEvent) Reset() {
	*x = TrackEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEvent) ProtoMessage() {}

func (x *TrackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEvent.ProtoReflect.Descriptor instead.
func (*TrackEvent) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{7}
}

type TrackPublicationInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid            string              `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid"`
	Name           string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Kind           TrackKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=openim.rtc.proto.TrackKind" json:"kind"`
	Source         TrackSource         `protobuf:"varint,4,opt,name=source,proto3,enum=openim.rtc.proto.TrackSource" json:"source"`
	Simulcasted    bool                `protobuf:"varint,5,opt,name=simulcasted,proto3" json:"simulcasted"`
	Width          uint32              `protobuf:"varint,6,opt,name=width,proto3" json:"width"`
	Height         uint32              `protobuf:"varint,7,opt,name=height,proto3" json:"height"`
	MimeType       string              `protobuf:"bytes,8,opt,name=mime_type,json=mimeType,proto3" json:"mime_type"`
	Muted          bool                `protobuf:"varint,9,opt,name=muted,proto3" json:"muted"`
	Remote         bool                `protobuf:"varint,10,opt,name=remote,proto3" json:"remote"`
	EncryptionType e2ee.EncryptionType `protobuf:"varint,11,opt,name=encryption_type,json=encryptionType,proto3,enum=openim.rtc.proto.EncryptionType" json:"encryption_type"`
}

func (x *TrackPublicationInfo) Reset() {
	*x = TrackPublicationInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackPublicationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackPublicationInfo) ProtoMessage() {}

func (x *TrackPublicationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackPublicationInfo.ProtoReflect.Descriptor instead.
func (*TrackPublicationInfo) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{8}
}

func (x *TrackPublicationInfo) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *TrackPublicationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrackPublicationInfo) GetKind() TrackKind {
	if x != nil {
		return x.Kind
	}
	return TrackKind_KIND_UNKNOWN
}

func (x *TrackPublicationInfo) GetSource() TrackSource {
	if x != nil {
		return x.Source
	}
	return TrackSource_SOURCE_UNKNOWN
}

func (x *TrackPublicationInfo) GetSimulcasted() bool {
	if x != nil {
		return x.Simulcasted
	}
	return false
}

func (x *TrackPublicationInfo) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TrackPublicationInfo) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TrackPublicationInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *TrackPublicationInfo) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *TrackPublicationInfo) GetRemote() bool {
	if x != nil {
		return x.Remote
	}
	return false
}

func (x *TrackPublicationInfo) GetEncryptionType() e2ee.EncryptionType {
	if x != nil {
		return x.EncryptionType
	}
	return e2ee.EncryptionType(0)
}

type OwnedTrackPublication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Handle *handle.FfiOwnedHandle `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle"`
	Info   *TrackPublicationInfo  `protobuf:"bytes,2,opt,name=info,proto3" json:"info"`
}

func (x *OwnedTrackPublication) Reset() {
	*x = OwnedTrackPublication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnedTrackPublication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedTrackPublication) ProtoMessage() {}

func (x *OwnedTrackPublication) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedTrackPublication.ProtoReflect.Descriptor instead.
func (*OwnedTrackPublication) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{9}
}

func (x *OwnedTrackPublication) GetHandle() *handle.FfiOwnedHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *OwnedTrackPublication) GetInfo() *TrackPublicationInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type TrackInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid         string      `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid"`
	Name        string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Kind        TrackKind   `protobuf:"varint,3,opt,name=kind,proto3,enum=openim.rtc.proto.TrackKind" json:"kind"`
	StreamState StreamState `protobuf:"varint,4,opt,name=stream_state,json=streamState,proto3,enum=openim.rtc.proto.StreamState" json:"stream_state"`
	Muted       bool        `protobuf:"varint,5,opt,name=muted,proto3" json:"muted"`
	Remote      bool        `protobuf:"varint,6,opt,name=remote,proto3" json:"remote"`
}

func (x *TrackInfo) Reset() {
	*x = TrackInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackInfo) ProtoMessage() {}

func (x *TrackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackInfo.ProtoReflect.Descriptor instead.
func (*TrackInfo) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{10}
}

func (x *TrackInfo) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *TrackInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrackInfo) GetKind() TrackKind {
	if x != nil {
		return x.Kind
	}
	return TrackKind_KIND_UNKNOWN
}

func (x *TrackInfo) GetStreamState() StreamState {
	if x != nil {
		return x.StreamState
	}
	return StreamState_STATE_UNKNOWN
}

func (x *TrackInfo) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *TrackInfo) GetRemote() bool {
	if x != nil {
		return x.Remote
	}
	return false
}

type OwnedTrack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Handle *handle.FfiOwnedHandle `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle"`
	Info   *TrackInfo             `protobuf:"bytes,2,opt,name=info,proto3" json:"info"`
}

func (x *OwnedTrack) Reset() {
	*x = OwnedTrack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnedTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnedTrack) ProtoMessage() {}

func (x *OwnedTrack) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnedTrack.ProtoReflect.Descriptor instead.
func (*OwnedTrack) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{11}
}

func (x *OwnedTrack) GetHandle() *handle.FfiOwnedHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *OwnedTrack) GetInfo() *TrackInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// Mute/UnMute a track
type LocalTrackMuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackHandle uint64 `protobuf:"varint,1,opt,name=track_handle,json=trackHandle,proto3" json:"track_handle"`
	Mute        bool   `protobuf:"varint,2,opt,name=mute,proto3" json:"mute"`
}

func (x *LocalTrackMuteRequest) Reset() {
	*x = LocalTrackMuteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalTrackMuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalTrackMuteRequest) ProtoMessage() {}

func (x *LocalTrackMuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalTrackMuteRequest.ProtoReflect.Descriptor instead.
func (*LocalTrackMuteRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{12}
}

func (x *LocalTrackMuteRequest) GetTrackHandle() uint64 {
	if x != nil {
		return x.TrackHandle
	}
	return 0
}

func (x *LocalTrackMuteRequest) GetMute() bool {
	if x != nil {
		return x.Mute
	}
	return false
}

type LocalTrackMuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Muted bool `protobuf:"varint,1,opt,name=muted,proto3" json:"muted"`
}

func (x *LocalTrackMuteResponse) Reset() {
	*x = LocalTrackMuteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalTrackMuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalTrackMuteResponse) ProtoMessage() {}

func (x *LocalTrackMuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalTrackMuteResponse.ProtoReflect.Descriptor instead.
func (*LocalTrackMuteResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{13}
}

func (x *LocalTrackMuteResponse) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

// Enable/Disable a remote track
type EnableRemoteTrackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackHandle uint64 `protobuf:"varint,1,opt,name=track_handle,json=trackHandle,proto3" json:"track_handle"`
	Enabled     bool   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled"`
}

func (x *EnableRemoteTrackRequest) Reset() {
	*x = EnableRemoteTrackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableRemoteTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRemoteTrackRequest) ProtoMessage() {}

func (x *EnableRemoteTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRemoteTrackRequest.ProtoReflect.Descriptor instead.
func (*EnableRemoteTrackRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{14}
}

func (x *EnableRemoteTrackRequest) GetTrackHandle() uint64 {
	if x != nil {
		return x.TrackHandle
	}
	return 0
}

func (x *EnableRemoteTrackRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type EnableRemoteTrackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled"`
}

func (x *EnableRemoteTrackResponse) Reset() {
	*x = EnableRemoteTrackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableRemoteTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRemoteTrackResponse) ProtoMessage() {}

func (x *EnableRemoteTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRemoteTrackResponse.ProtoReflect.Descriptor instead.
func (*EnableRemoteTrackResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{15}
}

func (x *EnableRemoteTrackResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetTrackSubscriptionPermissionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalParticipantHandle uint64                        `protobuf:"varint,1,opt,name=local_participant_handle,json=localParticipantHandle,proto3" json:"local_participant_handle"`
	AllParticipantsAllowed bool                          `protobuf:"varint,2,opt,name=all_participants_allowed,json=allParticipantsAllowed,proto3" json:"all_participants_allowed"`
	Permissions            []*ParticipantTrackPermission `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions"`
}

func (x *SetTrackSubscriptionPermissionsRequest) Reset() {
	*x = SetTrackSubscriptionPermissionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTrackSubscriptionPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTrackSubscriptionPermissionsRequest) ProtoMessage() {}

func (x *SetTrackSubscriptionPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTrackSubscriptionPermissionsRequest.ProtoReflect.Descriptor instead.
func (*SetTrackSubscriptionPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{16}
}

func (x *SetTrackSubscriptionPermissionsRequest) GetLocalParticipantHandle() uint64 {
	if x != nil {
		return x.LocalParticipantHandle
	}
	return 0
}

func (x *SetTrackSubscriptionPermissionsRequest) GetAllParticipantsAllowed() bool {
	if x != nil {
		return x.AllParticipantsAllowed
	}
	return false
}

func (x *SetTrackSubscriptionPermissionsRequest) GetPermissions() []*ParticipantTrackPermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ParticipantTrackPermission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The participant identity this permission applies to.
	ParticipantIdentity string `protobuf:"bytes,1,opt,name=participant_identity,json=participantIdentity,proto3" json:"participant_identity"`
	// Grant permission to all all tracks. Takes precedence over allowedTrackSids.
	AllowAll bool `protobuf:"varint,2,opt,name=allow_all,json=allowAll,proto3" json:"allow_all"`
	// List of track sids to grant permission to.
	AllowedTrackSids []string `protobuf:"bytes,3,rep,name=allowed_track_sids,json=allowedTrackSids,proto3" json:"allowed_track_sids"`
}

func (x *ParticipantTrackPermission) Reset() {
	*x = ParticipantTrackPermission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParticipantTrackPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantTrackPermission) ProtoMessage() {}

func (x *ParticipantTrackPermission) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantTrackPermission.ProtoReflect.Descriptor instead.
func (*ParticipantTrackPermission) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{17}
}

func (x *ParticipantTrackPermission) GetParticipantIdentity() string {
	if x != nil {
		return x.ParticipantIdentity
	}
	return ""
}

func (x *ParticipantTrackPermission) GetAllowAll() bool {
	if x != nil {
		return x.AllowAll
	}
	return false
}

func (x *ParticipantTrackPermission) GetAllowedTrackSids() []string {
	if x != nil {
		return x.AllowedTrackSids
	}
	return nil
}

type SetTrackSubscriptionPermissionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetTrackSubscriptionPermissionsResponse) Reset() {
	*x = SetTrackSubscriptionPermissionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_track_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTrackSubscriptionPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTrackSubscriptionPermissionsResponse) ProtoMessage() {}

func (x *SetTrackSubscriptionPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTrackSubscriptionPermissionsResponse.ProtoReflect.Descriptor instead.
func (*SetTrackSubscriptionPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{18}
}

var File_track_proto protoreflect.FileDescriptor

var file_track_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0a, 0x65, 0x32, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x4e, 0x0a, 0x18, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72,
	0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x22, 0x52, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x4e,
	0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x74, 0x72,
	0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x77, 0x6e,
	0x65, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x22, 0x34,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x22, 0x2d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x79, 0x6e,
	0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x73, 0x79, 0x6e,
	0x63, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x43,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x79, 0x6e, 0x63,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x73, 0x79, 0x6e, 0x63,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d,
	0x2e, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x74, 0x63, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x8a, 0x03, 0x0a, 0x14, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72,
	0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4b, 0x69,
	0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69,
	0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x63, 0x61, 0x73, 0x74, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x63, 0x61, 0x73, 0x74, 0x65,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d, 0x75, 0x74,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x49, 0x0a, 0x0f, 0x65, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x15, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x38, 0x0a, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x46, 0x66, 0x69, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x52, 0x06, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d,
	0x2e, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d,
	0x2e, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x40, 0x0a, 0x0c, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d, 0x75, 0x74,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x22, 0x77, 0x0a, 0x0a, 0x4f, 0x77,
	0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x38, 0x0a, 0x06, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69,
	0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x66, 0x69, 0x4f,
	0x77, 0x6e, 0x65, 0x64, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x06, 0x68, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x2e, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x4e, 0x0a, 0x15, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x4d, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6d,
	0x75, 0x74, 0x65, 0x22, 0x2e, 0x0a, 0x16, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x4d, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d, 0x75,
	0x74, 0x65, 0x64, 0x22, 0x57, 0x0a, 0x18, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x35, 0x0a, 0x19,
	0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x22, 0xec, 0x01, 0x0a, 0x26, 0x53, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38,
	0x0a, 0x18, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x16, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x18, 0x61, 0x6c, 0x6c, 0x5f,
	0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x5f, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x61, 0x6c, 0x6c, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x12, 0x4e, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d,
	0x2e, 0x72, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x1a, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6e, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x31, 0x0a, 0x14, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x13, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x61, 0x6c,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x41, 0x6c,
	0x6c, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x5f, 0x73, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x69, 0x64, 0x73, 0x22,
	0x29, 0x0a, 0x27, 0x53, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x3d, 0x0a, 0x09, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x0c, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x02, 0x2a, 0x81, 0x01, 0x0a, 0x0b, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x4f, 0x55,
	0x52, 0x43, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x43, 0x41, 0x4d, 0x45, 0x52, 0x41, 0x10, 0x01,
	0x12, 0x15, 0x0a, 0x11, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x4d, 0x49, 0x43, 0x52, 0x4f,
	0x50, 0x48, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x4f, 0x55, 0x52, 0x43,
	0x45, 0x5f, 0x53, 0x43, 0x52, 0x45, 0x45, 0x4e, 0x53, 0x48, 0x41, 0x52, 0x45, 0x10, 0x03, 0x12,
	0x1c, 0x0a, 0x18, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x53, 0x43, 0x52, 0x45, 0x45, 0x4e,
	0x53, 0x48, 0x41, 0x52, 0x45, 0x5f, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x04, 0x2a, 0x44, 0x0a,
	0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x11, 0x0a, 0x0d,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10,
	0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x41, 0x55, 0x53, 0x45,
	0x44, 0x10, 0x02, 0x42, 0x40, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6d, 0x73, 0x64, 0x6b, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x6d, 0x2d, 0x72, 0x74, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0xaa, 0x02, 0x0d, 0x4c, 0x69, 0x76, 0x65, 0x4b, 0x69, 0x74, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_track_proto_rawDescOnce sync.Once
	file_track_proto_rawDescData = file_track_proto_rawDesc
)

func file_track_proto_rawDescGZIP() []byte {
	file_track_proto_rawDescOnce.Do(func() {
		file_track_proto_rawDescData = protoimpl.X.CompressGZIP(file_track_proto_rawDescData)
	})
	return file_track_proto_rawDescData
}

var file_track_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_track_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_track_proto_goTypes = []any{
	(TrackKind)(0),                                  // 0: openim.rtc.proto.TrackKind
	(TrackSource)(0),                                // 1: openim.rtc.proto.TrackSource
	(StreamState)(0),                                // 2: openim.rtc.proto.StreamState
	(*CreateVideoTrackRequest)(nil),                 // 3: openim.rtc.proto.CreateVideoTrackRequest
	(*CreateVideoTrackResponse)(nil),                // 4: openim.rtc.proto.CreateVideoTrackResponse
	(*CreateAudioTrackRequest)(nil),                 // 5: openim.rtc.proto.CreateAudioTrackRequest
	(*CreateAudioTrackResponse)(nil),                // 6: openim.rtc.proto.CreateAudioTrackResponse
	(*GetStatsRequest)(nil),                         // 7: openim.rtc.proto.GetStatsRequest
	(*GetStatsResponse)(nil),                        // 8: openim.rtc.proto.GetStatsResponse
	(*GetStatsCallback)(nil),                        // 9: openim.rtc.proto.GetStatsCallback
	(*TrackEvent)(nil),                              // 10: openim.rtc.proto.TrackEvent
	(*TrackPublicationInfo)(nil),                    // 11: openim.rtc.proto.TrackPublicationInfo
	(*OwnedTrackPublication)(nil),                   // 12: openim.rtc.proto.OwnedTrackPublication
	(*TrackInfo)(nil),                               // 13: openim.rtc.proto.TrackInfo
	(*OwnedTrack)(nil),                              // 14: openim.rtc.proto.OwnedTrack
	(*LocalTrackMuteRequest)(nil),                   // 15: openim.rtc.proto.LocalTrackMuteRequest
	(*LocalTrackMuteResponse)(nil),                  // 16: openim.rtc.proto.LocalTrackMuteResponse
	(*EnableRemoteTrackRequest)(nil),                // 17: openim.rtc.proto.EnableRemoteTrackRequest
	(*EnableRemoteTrackResponse)(nil),               // 18: openim.rtc.proto.EnableRemoteTrackResponse
	(*SetTrackSubscriptionPermissionsRequest)(nil),  // 19: openim.rtc.proto.SetTrackSubscriptionPermissionsRequest
	(*ParticipantTrackPermission)(nil),              // 20: openim.rtc.proto.ParticipantTrackPermission
	(*SetTrackSubscriptionPermissionsResponse)(nil), // 21: openim.rtc.proto.SetTrackSubscriptionPermissionsResponse
	(*stats.RtcStats)(nil),                          // 22: openim.rtc.proto.RtcStats
	(e2ee.EncryptionType)(0),                        // 23: openim.rtc.proto.EncryptionType
	(*handle.FfiOwnedHandle)(nil),                   // 24: openim.rtc.proto.FfiOwnedHandle
}
var file_track_proto_depIdxs = []int32{
	14, // 0: openim.rtc.proto.CreateVideoTrackResponse.track:type_name -> openim.rtc.proto.OwnedTrack
	14, // 1: openim.rtc.proto.CreateAudioTrackResponse.track:type_name -> openim.rtc.proto.OwnedTrack
	22, // 2: openim.rtc.proto.GetStatsCallback.stats:type_name -> openim.rtc.proto.RtcStats
	0,  // 3: openim.rtc.proto.TrackPublicationInfo.kind:type_name -> openim.rtc.proto.TrackKind
	1,  // 4: openim.rtc.proto.TrackPublicationInfo.source:type_name -> openim.rtc.proto.TrackSource
	23, // 5: openim.rtc.proto.TrackPublicationInfo.encryption_type:type_name -> openim.rtc.proto.EncryptionType
	24, // 6: openim.rtc.proto.OwnedTrackPublication.handle:type_name -> openim.rtc.proto.FfiOwnedHandle
	11, // 7: openim.rtc.proto.OwnedTrackPublication.info:type_name -> openim.rtc.proto.TrackPublicationInfo
	0,  // 8: openim.rtc.proto.TrackInfo.kind:type_name -> openim.rtc.proto.TrackKind
	2,  // 9: openim.rtc.proto.TrackInfo.stream_state:type_name -> openim.rtc.proto.StreamState
	24, // 10: openim.rtc.proto.OwnedTrack.handle:type_name -> openim.rtc.proto.FfiOwnedHandle
	13, // 11: openim.rtc.proto.OwnedTrack.info:type_name -> openim.rtc.proto.TrackInfo
	20, // 12: openim.rtc.proto.SetTrackSubscriptionPermissionsRequest.permissions:type_name -> openim.rtc.proto.ParticipantTrackPermission
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_track_proto_init() }
func file_track_proto_init() {
	if File_track_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_track_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateVideoTrackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateVideoTrackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAudioTrackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAudioTrackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatsCallback); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*TrackEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*TrackPublicationInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*OwnedTrackPublication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*TrackInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*OwnedTrack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*LocalTrackMuteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*LocalTrackMuteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*EnableRemoteTrackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*EnableRemoteTrackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*SetTrackSubscriptionPermissionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*ParticipantTrackPermission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_track_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*SetTrackSubscriptionPermissionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_track_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_track_proto_goTypes,
		DependencyIndexes: file_track_proto_depIdxs,
		EnumInfos:         file_track_proto_enumTypes,
		MessageInfos:      file_track_proto_msgTypes,
	}.Build()
	File_track_proto = out.File
	file_track_proto_rawDesc = nil
	file_track_proto_goTypes = nil
	file_track_proto_depIdxs = nil
}
